(in-package #:zed)

(defstruct (config
            (:predicate nil)
            (:copier nil))
  (profile-p nil :type boolean)
  (frame-count nil :type (or (and (integer 1) fixnum) boolean))
  (prelude (constantly nil) :type (or function symbol))
  (window-width 1280 :type u:ub16)
  (window-height 720 :type u:ub16)
  (window-title "Zed Engine" :type string)
  (anti-alias-p t :type boolean)
  (delta-time nil :type (or real null))
  (log-repl-level :debug :type keyword)
  (log-repl-categories '(:zed) :type list)
  (collision-plan nil :type symbol))
