(in-package #:defpackage+-user-1)

(defpackage+ #:zed.shader-library
  (:local-nicknames
   (#:u #:golden-utils))
  (:inherit #:shadow.glsl)
  ;; Common
  (:export
   #:camera-data
   #:camera/view
   #:camera/proj
   #:mesh-attrs
   #:mesh/pos
   #:mesh/normal
   #:mesh/tangent
   #:mesh/color
   #:mesh/uv1
   #:mesh/uv2
   #:mesh/joints
   #:mesh/weights
   #:mvlet*
   #:saturate)
  ;; Color functions
  (:export
   #:color-filter
   #:hcy->rgb
   #:hsl->rgb
   #:hsv->rgb
   #:hue->rgb
   #:rgb->grayscale
   #:rgb->hcv
   #:rgb->hcy
   #:rgb->hsl
   #:rgb->hsv
   #:rgb->srgb
   #:rgb->srgb-approx
   #:rgb->xyy
   #:rgb->xyz
   #:set-brightness
   #:set-contrast
   #:set-exposure
   #:set-gamma
   #:set-saturation
   #:srgb->rgb
   #:srgb->rgb-approx
   #:tone-map/aces
   #:tone-map/haarm-peter-duiker
   #:tone-map/hejl-burgess-dawson
   #:tone-map/linear
   #:tone-map/reinhard
   #:tone-map/uncharted2
   #:xyy->rgb
   #:xyy->xyz
   #:xyz->rgb
   #:xyz->xyy)
  ;; Shaping functions
  (:export
   #:almost-identity
   #:back-in
   #:back-in-out
   #:back-out
   #:blinn-wyvill-raised-inverted-cosine
   #:bounce-in
   #:bounce-in-out
   #:bounce-out
   #:circular-in
   #:circular-in-out
   #:circular-out
   #:cubic-in
   #:cubic-in-out
   #:cubic-out
   #:cubic-pulse
   #:double-circle-seat
   #:double-circle-sigmoid
   #:double-cubic-seat
   #:double-cubic-seat/linear-blend
   #:double-elliptical-seat
   #:double-elliptical-sigmoid
   #:double-exponential-seat
   #:double-exponential-sigmoid
   #:double-odd-polynomial-seat
   #:elastic-in
   #:elastic-in-out
   #:elastic-out
   #:exponential-emphasis
   #:exponential-in
   #:exponential-in-out
   #:exponential-out
   #:exponential-step
   #:falloff-squared-c1
   #:falloff-squared-c2
   #:gain
   #:hermite-curve
   #:impulse
   #:linear
   #:logistic-sigmoid
   #:parabola
   #:power-curve
   #:quadratic-in
   #:quadratic-in-out
   #:quadratic-out
   #:quadratic-point
   #:quartic-in
   #:quartic-in-out
   #:quartic-out
   #:quintic-curve
   #:quintic-curve/derivative
   #:quintic-curve/fast
   #:quintic-curve/interpolate-derivative
   #:quintic-hermite
   #:quintic-hermite/derivative
   #:quintic-in
   #:quintic-in-out
   #:quintic-out
   #:sinc-curve
   #:sine-in
   #:sine-in-out
   #:sine-out)
  ;; Programs
  (:export
   #:default
   #:font
   #:matcap
   #:sprite))
