(in-package #:defpackage+-user-1)

(defpackage+ #:zed.shader-library
  (:local-nicknames
   (#:u #:golden-utils))
  (:inherit #:shadow.glsl)
  ;; Common
  (:export
   #:camera-data
   #:camera/view
   #:camera/proj
   #:mesh-attrs
   #:mesh/pos
   #:mesh/normal
   #:mesh/tangent
   #:mesh/color
   #:mesh/uv1
   #:mesh/uv2
   #:mesh/joints
   #:mesh/weights
   #:mvlet*
   #:saturate)
  ;; Color functions
  (:export
   #:color/filter
   #:color/hcy->rgb
   #:color/hsl->rgb
   #:color/hsv->rgb
   #:color/hue->rgb
   #:color/rgb->grayscale
   #:color/rgb->hcv
   #:color/rgb->hcy
   #:color/rgb->hsl
   #:color/rgb->hsv
   #:color/rgb->srgb
   #:color/rgb->srgb-approx
   #:color/rgb->xyy
   #:color/rgb->xyz
   #:color/set-brightness
   #:color/set-contrast
   #:color/set-exposure
   #:color/set-gamma
   #:color/set-saturation
   #:color/srgb->rgb
   #:color/srgb->rgb-approx
   #:color/tone-map-aces
   #:color/tone-map-haarm-peter-duiker
   #:color/tone-map-hejl-burgess-dawson
   #:color/tone-map-linear
   #:color/tone-map-reinhard
   #:color/tone-map-uncharted2
   #:color/xyy->rgb
   #:color/xyy->xyz
   #:color/xyz->rgb
   #:color/xyz->xyy)
  ;; Shaping functions
  (:export
   #:shape/almost-identity
   #:shape/back-in
   #:shape/back-in-out
   #:shape/back-out
   #:shape/blinn-wyvill-raised-inverted-cosine
   #:shape/bounce-in
   #:shape/bounce-in-out
   #:shape/bounce-out
   #:shape/circular-in
   #:shape/circular-in-out
   #:shape/circular-out
   #:shape/cubic-in
   #:shape/cubic-in-out
   #:shape/cubic-out
   #:shape/cubic-pulse
   #:shape/double-circle-seat
   #:shape/double-circle-sigmoid
   #:shape/double-cubic-seat
   #:shape/double-cubic-seat-linear-blend
   #:shape/double-elliptical-seat
   #:shape/double-elliptical-sigmoid
   #:shape/double-exponential-seat
   #:shape/double-exponential-sigmoid
   #:shape/double-odd-polynomial-seat
   #:shape/elastic-in
   #:shape/elastic-in-out
   #:shape/elastic-out
   #:shape/exponential-emphasis
   #:shape/exponential-in
   #:shape/exponential-in-out
   #:shape/exponential-out
   #:shape/exponential-step
   #:shape/falloff-squared-c1
   #:shape/falloff-squared-c2
   #:shape/gain
   #:shape/hermite-curve
   #:shape/impulse
   #:shape/linear
   #:shapelogistic-sigmoid
   #:shape/parabola
   #:shape/power-curve
   #:shape/quadratic-in
   #:shape/quadratic-in-out
   #:shape/quadratic-out
   #:shape/quadratic-point
   #:shape/quartic-in
   #:shape/quartic-in-out
   #:shape/quartic-out
   #:shape/quintic-curve
   #:shape/quintic-curve-derivative
   #:shape/quintic-curve-fast
   #:shape/quintic-curve-interpolate-derivative
   #:shape/quintic-hermite
   #:shape/quintic-hermite-derivative
   #:shape/quintic-in
   #:shape/quintic-in-out
   #:shape/quintic-out
   #:shape/sinc-curve
   #:shape/sine-in
   #:shape/sine-in-out
   #:shape/sine-out)
  ;; Hashing functions
  (:export
   #:hash/bbs
   #:hash/bbs-hq
   #:hash/fast32
   #:hash/fast32-2-per-corner
   #:hash/fast32-3-per-corner
   #:hash/fast32-4-per-corner
   #:hash/fast32-cell
   #:hash/fast32-2
   #:hash/fast32-2-4-per-corner
   #:hash/sgpp
   #:hash/sgpp-2-per-corner
   #:hash/sgpp-3-per-corner)
  ;; Noise functions
  (:export
   #:noise/billow-cellular
   #:noise/billow-perlin
   #:noise/billow-simplex
   #:noise/cellular
   #:noise/cellular-derivs
   #:noise/cellular-fast
   #:noise/cubist
   #:noise/fbm-cellular
   #:noise/fbm-perlin
   #:noise/fbm-simplex
   #:noise/hermite
   #:noise/hermite-derivs
   #:noise/perlin
   #:noise/perlin-derivs
   #:noise/perlin-improved
   #:noise/perlin-surflet
   #:noise/perlin-surflet-derivs
   #:noise/polkadot
   #:noise/polkadot-box
   #:noise/ridges-cellular
   #:noise/ridges-perlin
   #:noise/ridges-simplex
   #:noise/simplex-cellular
   #:noise/simplex
   #:noise/simplex-derivs
   #:noise/simplex-polkadot
   #:noise/stars
   #:noise/value
   #:noise/value-derivs
   #:noise/value-hermite
   #:noise/value-perlin)
  ;; SDF functions
  (:export
   #:sdf/arc
   #:sdf/box
   #:sdf/circle
   #:sdf/cross
   #:sdf/difference
   #:sdf/difference-smooth
   #:sdf/egg
   #:sdf/hexagon
   #:sdf/intersect
   #:sdf/intersect-smooth
   #:sdf/mask-fill
   #:sdf/mask-inner-border
   #:sdf/mask-outer-border
   #:sdf/onion
   #:sdf/parabola
   #:sdf/pentagon
   #:sdf/pie
   #:sdf/rhombus
   #:sdf/rounded-x
   #:sdf/segment
   #:sdf/semi-circle
   #:sdf/shadow
   #:sdf/star
   #:sdf/star5
   #:sdf/star6
   #:sdf/trapezoid
   #:sdf/triangle
   #:sdf/uneven-capsule
   #:sdf/union
   #:sdf/union-smooth
   #:sdf/vesica)
  ;; Programs
  (:export
   #:default
   #:font
   #:matcap
   #:sprite))
