(in-package #:defpackage+-user-1)

(defpackage+ #:zed.shader-library
  (:local-nicknames
   (#:u #:golden-utils))
  (:inherit #:shadow.glsl)
  ;; Common
  (:export
   #:camera-data
   #:camera/view
   #:camera/proj
   #:mesh-attrs
   #:mesh/pos
   #:mesh/normal
   #:mesh/tangent
   #:mesh/color
   #:mesh/uv1
   #:mesh/uv2
   #:mesh/joints
   #:mesh/weights
   #:mvlet*
   #:saturate)
  ;; Color functions
  (:export
   #:color-filter
   #:hcy->rgb
   #:hsl->rgb
   #:hsv->rgb
   #:hue->rgb
   #:rgb->grayscale
   #:rgb->hcv
   #:rgb->hcy
   #:rgb->hsl
   #:rgb->hsv
   #:rgb->srgb
   #:rgb->srgb-approx
   #:rgb->xyy
   #:rgb->xyz
   #:set-brightness
   #:set-contrast
   #:set-exposure
   #:set-gamma
   #:set-saturation
   #:srgb->rgb
   #:srgb->rgb-approx
   #:tone-map/aces
   #:tone-map/haarm-peter-duiker
   #:tone-map/hejl-burgess-dawson
   #:tone-map/linear
   #:tone-map/reinhard
   #:tone-map/uncharted2
   #:xyy->rgb
   #:xyy->xyz
   #:xyz->rgb
   #:xyz->xyy)
  ;; Shaping functions
  (:export
   #:almost-identity
   #:back-in
   #:back-in-out
   #:back-out
   #:blinn-wyvill-raised-inverted-cosine
   #:bounce-in
   #:bounce-in-out
   #:bounce-out
   #:circular-in
   #:circular-in-out
   #:circular-out
   #:cubic-in
   #:cubic-in-out
   #:cubic-out
   #:cubic-pulse
   #:double-circle-seat
   #:double-circle-sigmoid
   #:double-cubic-seat
   #:double-cubic-seat/linear-blend
   #:double-elliptical-seat
   #:double-elliptical-sigmoid
   #:double-exponential-seat
   #:double-exponential-sigmoid
   #:double-odd-polynomial-seat
   #:elastic-in
   #:elastic-in-out
   #:elastic-out
   #:exponential-emphasis
   #:exponential-in
   #:exponential-in-out
   #:exponential-out
   #:exponential-step
   #:falloff-squared-c1
   #:falloff-squared-c2
   #:gain
   #:hermite-curve
   #:impulse
   #:linear
   #:logistic-sigmoid
   #:parabola
   #:power-curve
   #:quadratic-in
   #:quadratic-in-out
   #:quadratic-out
   #:quadratic-point
   #:quartic-in
   #:quartic-in-out
   #:quartic-out
   #:quintic-curve
   #:quintic-curve/derivative
   #:quintic-curve/fast
   #:quintic-curve/interpolate-derivative
   #:quintic-hermite
   #:quintic-hermite/derivative
   #:quintic-in
   #:quintic-in-out
   #:quintic-out
   #:sinc-curve
   #:sine-in
   #:sine-in-out
   #:sine-out)
  ;; Hashing functions
  (:export
   #:blum-blum-shub
   #:blum-blum-shub/hq
   #:fast32
   #:fast32/2-per-corner
   #:fast32/3-per-corner
   #:fast32/4-per-corner
   #:fast32/cell
   #:fast32-2
   #:fast32-2/4-per-corner
   #:sgpp
   #:sgpp/2-per-corner
   #:sgpp/3-per-corner)
  ;; Noise functions
  (:export
   #:noise/billow-cellular
   #:noise/billow-perlin
   #:noise/billow-simplex
   #:noise/cellular
   #:noise/cellular-derivs
   #:noise/cellular-fast
   #:noise/cubist
   #:noise/fbm-cellular
   #:noise/fbm-perlin
   #:noise/fbm-simplex
   #:noise/hermite
   #:noise/hermite-derivs
   #:noise/perlin
   #:noise/perlin-derivs
   #:noise/perlin-improved
   #:noise/perlin-surflet
   #:noise/perlin-surflet-derivs
   #:noise/polkadot
   #:noise/polkadot-box
   #:noise/ridges-cellular
   #:noise/ridges-perlin
   #:noise/ridges-simplex
   #:noise/simplex-cellular
   #:noise/simplex-perlin
   #:noise/simplex-perlin-derivs
   #:noise/simplex-polkadot
   #:noise/stars
   #:noise/value
   #:noise/value-derivs
   #:noise/value-hermite
   #:noise/value-perlin)
  ;; SDF functions
  (:export
   #:sdf/arc
   #:sdf/box
   #:sdf/circle
   #:sdf/cross
   #:sdf/difference
   #:sdf/difference-smooth
   #:sdf/egg
   #:sdf/hexagon
   #:sdf/intersect
   #:sdf/intersect-smooth
   #:sdf/mask-fill
   #:sdf/mask-inner-border
   #:sdf/mask-outer-border
   #:sdf/onion
   #:sdf/parabola
   #:sdf/pentagon
   #:sdf/pie
   #:sdf/rhombus
   #:sdf/rounded-x
   #:sdf/segment
   #:sdf/semi-circle
   #:sdf/shadow
   #:sdf/star
   #:sdf/star5
   #:sdf/star6
   #:sdf/trapezoid
   #:sdf/triangle
   #:sdf/uneven-capsule
   #:sdf/union
   #:sdf/union-smooth
   #:sdf/vesica)
  ;; Programs
  (:export
   #:default
   #:font
   #:matcap
   #:sprite))
